// <auto-generated />
using Kaffi.Backend.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kaffi.Backend.Data.Migrations
{
    [DbContext(typeof(KaffiContext))]
    partial class KaffiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Coffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("countryid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("VarietyId")
                        .HasColumnType("integer")
                        .HasColumnName("varietyid");

                    b.HasKey("Id")
                        .HasName("pk_coffee");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_coffee_countryid");

                    b.HasIndex("VarietyId")
                        .HasDatabaseName("ix_coffee_varietyid");

                    b.ToTable("coffee", (string)null);
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Coffee_Flavour", b =>
                {
                    b.Property<int>("CoffeeId")
                        .HasColumnType("integer")
                        .HasColumnName("coffeeid");

                    b.Property<int>("FlavourId")
                        .HasColumnType("integer")
                        .HasColumnName("flavourid");

                    b.HasKey("CoffeeId", "FlavourId")
                        .HasName("pk_coffee_flavours");

                    b.HasIndex("FlavourId")
                        .HasDatabaseName("ix_coffee_flavours_flavourid");

                    b.ToTable("coffee_flavours", (string)null);
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_continent");

                    b.ToTable("continent", (string)null);
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContinentId")
                        .HasColumnType("integer")
                        .HasColumnName("continentid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.HasIndex("ContinentId")
                        .HasDatabaseName("ix_country_continentid");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Flavour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_flavour");

                    b.ToTable("flavour", (string)null);
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Variety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_variety");

                    b.ToTable("variety", (string)null);
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Coffee", b =>
                {
                    b.HasOne("Kaffi.Backend.Code.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coffee_country_countryid");

                    b.HasOne("Kaffi.Backend.Code.Entities.Variety", "Variety")
                        .WithMany()
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coffee_variety_varietyid");

                    b.Navigation("Country");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Coffee_Flavour", b =>
                {
                    b.HasOne("Kaffi.Backend.Code.Entities.Coffee", "Coffee")
                        .WithMany("CoffeeFlavours")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coffee_flavours_coffee_coffeeid");

                    b.HasOne("Kaffi.Backend.Code.Entities.Flavour", "Flavour")
                        .WithMany()
                        .HasForeignKey("FlavourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coffee_flavours_flavour_flavourid");

                    b.Navigation("Coffee");

                    b.Navigation("Flavour");
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Country", b =>
                {
                    b.HasOne("Kaffi.Backend.Code.Entities.Continent", "Continent")
                        .WithMany()
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_country_continent_continentid");

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("Kaffi.Backend.Code.Entities.Coffee", b =>
                {
                    b.Navigation("CoffeeFlavours");
                });
#pragma warning restore 612, 618
        }
    }
}
